{
 "title": "OLT",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "content": "<center><img src=\"https://wdcnet.com.br/wp-content/uploads/2019/02/fiberhome-ajustado-500x333.png\" width=\"200\"/></center/>",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Endereço IP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "Endereço IP" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Download",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": {
      "filter": "Interface sfp-sfpplus2(========== PTP OLT ==========)"
     },
     "group": { "filter": "CE" },
     "host": { "filter": "CE - PCP FTTH" },
     "item": {
      "filter": "Interface sfp-sfpplus2(========== PTP OLT ==========): Bits sent"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Upload",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": {
      "filter": "Interface sfp-sfpplus2(========== PTP OLT ==========)"
     },
     "group": { "filter": "CE" },
     "host": { "filter": "CE - PCP FTTH" },
     "item": {
      "filter": "Interface sfp-sfpplus2(========== PTP OLT ==========): Bits received"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Endereço MAC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "Endereço MAC" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "content": "<center><h1>OLT-001</h1></center/>",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 20, "x": 4, "y": 6 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "GC8B[1]",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 4, "y": 7 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "GC8B[2]",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 8, "y": 7 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "GC8B[3]",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 12, "y": 7 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "GC8B[4]",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 16, "y": 7 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "GC8B[5]",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 7 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo de Resposta",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "ICMP response time" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "PON" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "Total de ONU's PON 1" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "PON" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "Total de ONU's PON 2" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "PON" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "Total de ONU's PON 3" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "PON" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "Total de ONU's PON 4" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "PON" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "Total de ONU's PON 5" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:144",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 1/1" ],
       "text": "setAlias(PON 1/1)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 1/1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:158",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 1/2" ],
       "text": "setAlias(PON 1/2)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 1/2"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:172",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 1/3" ],
       "text": "setAlias(PON 1/3)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 1/3"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:186",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 1/4" ],
       "text": "setAlias(PON 1/4)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 1/4"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:200",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 1/5" ],
       "text": "setAlias(PON 1/5)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 1/5"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:214",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 1/6" ],
       "text": "setAlias(PON 1/6)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 1/6"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:228",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 1/7" ],
       "text": "setAlias(PON 1/7)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 1/7"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:242",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 1/8" ],
       "text": "setAlias(PON 1/8)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 1/8"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:470",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 2/1" ],
       "text": "setAlias(PON 2/1)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 2/1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:484",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 2/2" ],
       "text": "setAlias(PON 2/2)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 2/2"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:498",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 2/3" ],
       "text": "setAlias(PON 2/3)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 2/3"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:512",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 2/4" ],
       "text": "setAlias(PON 2/4)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 2/4"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:526",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 2/5" ],
       "text": "setAlias(PON 2/5)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 2/5"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:540",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 2/6" ],
       "text": "setAlias(PON 2/6)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 2/6"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:554",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 2/7" ],
       "text": "setAlias(PON 2/7)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 2/7"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:568",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 2/8" ],
       "text": "setAlias(PON 2/8)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 2/8"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:806",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 3/1" ],
       "text": "setAlias(PON 3/1)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 3/1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:820",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 3/2" ],
       "text": "setAlias(PON 3/2)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 3/2"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:834",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 3/3" ],
       "text": "setAlias(PON 3/3)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 3/3"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:848",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 3/4" ],
       "text": "setAlias(PON 3/4)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 3/4"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:862",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 3/5" ],
       "text": "setAlias(PON 3/5)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 3/5"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:876",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 3/6" ],
       "text": "setAlias(PON 3/6)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 3/6"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:890",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 3/7" ],
       "text": "setAlias(PON 3/7)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 3/7"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:904",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 3/8" ],
       "text": "setAlias(PON 3/8)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 3/8"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:974",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 4/1" ],
       "text": "setAlias(PON 4/1)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 4/1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:988",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 4/2" ],
       "text": "setAlias(PON 4/2)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 4/2"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:1002",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 4/3" ],
       "text": "setAlias(PON 4/3)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 4/3"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:1016",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 4/4" ],
       "text": "setAlias(PON 4/4)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 4/4"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:1030",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 4/5" ],
       "text": "setAlias(PON 4/5)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 4/5"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:1044",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 4/6" ],
       "text": "setAlias(PON 4/6)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 4/6"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:1058",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 4/7" ],
       "text": "setAlias(PON 4/7)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 4/7"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:1072",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 4/8" ],
       "text": "setAlias(PON 4/8)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 4/8"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:1142",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 5/1" ],
       "text": "setAlias(PON 5/1)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 5/1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:1156",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 5/2" ],
       "text": "setAlias(PON 5/2)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 5/2"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:1170",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 5/3" ],
       "text": "setAlias(PON 5/3)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 5/3"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:1184",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 5/4" ],
       "text": "setAlias(PON 5/4)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 5/4"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:1198",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 5/5" ],
       "text": "setAlias(PON 5/5)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 5/5"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:1212",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 5/6" ],
       "text": "setAlias(PON 5/6)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 5/6"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:1226",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 5/7" ],
       "text": "setAlias(PON 5/7)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 5/7"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "$$hashKey": "object:1240",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PON 5/8" ],
       "text": "setAlias(PON 5/8)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": {
      "filter": "Numero de ONU's na porta PON 5/8"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Informações do Sistema" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "Temperatura" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total de ONU's",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "PON" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "Total de ONU's OLT-001" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "V. Soft.",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "Versão de Software GC8B[1]" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "V. Hard.",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "Versão de Hardware GC8B[1]" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "V. Soft.",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "Versão de Software GC8B[2]" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "V. Hard.",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "Versão de Hardware GC8B[2]" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "V. Soft.",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "Versão de Software GC8B[3]" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "V. Hard.",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "Versão de Hardware GC8B[3]" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "V. Soft.",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "Versão de Software GC8B[4]" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "V. Hard.",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "Versão de Hardware GC8B[4]" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "V. Soft.",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "Versão de Software GC8B[5]" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "V. Hard.",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT Fiberhome" },
     "item": { "filter": "Versão de Hardware GC8B[5]" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}